### ISSUE TITLE
How are we going to store each day's value for an item for value:time graph?

### ISSUE THREAD

**Issue by Nathan-Schwartz** [TeamCommercium/invenstory#101]

**Comment by djake** [comment]
haven't implemented. /inventory/list can take an argument to filter by a specific product. i say we include an array of objects with the historical data in that case, which could be used to populate a detail view. does that work?

**Comment by Nathan-Schwartz** [comment]
That sounds good

**Comment by Nathan-Schwartz** [comment]
One limitation this solution could have is that the feature would be useless to a new user. Maybe we could pull historical data about the item from somewhere? (non-MVP)
